import { defineMeeting } from "./builders";

/**
 * The case that matters most for a notetaker: eight people, an hour, many
 * threads. It exercises speaker lanes, chapters, search, and Ask at scale.
 */
export const launchGoNoGo = defineMeeting({
  id: "launch-go-no-go",
  title: "Launch Go/No-Go: October 20",
  date: "2026-09-22T15:00:00Z",
  duration: "1:02:40",
  meetingType: "Product",
  platform: "zoom",
  hostId: "olivia",
  participants: ["olivia", "hammad", "sarah", "marcus", "priya", "tom", "emily", "diego"],
  template: "product",
  tags: ["launch", "sso", "performance", "go-no-go"],
  tone: "Candid · decision-focused",
  summary:
    "Eight leads reviewed readiness for the October 20 enterprise launch area by area. Engineering reported SAML SSO feature-complete for Okta and Google Workspace, with Azure AD still failing on multi-tenant apps, and the dashboard regression down from 4.1 to 1.3 seconds at p95 with a 900 ms target. The group decided launch is a conditional go: SSO ships for all three identity providers or Azure AD is labelled beta, the performance fix must hit target by October 13, and the October 27 fallback is triggered automatically if either gate misses. Marketing keeps the data summit keynote, sales holds Acme's pilot to the launch build, and customer success starts beta migrations on October 14.",
  keyDecisions: [
    "Launch is a conditional go for October 20, with two gates checked on October 13: dashboard p95 under 900 ms and Azure AD SSO passing the beta tenants.",
    "If Azure AD isn't stable by October 13, SSO launches for Okta and Google Workspace and Azure AD ships labelled beta.",
    "If the performance gate misses, the launch moves to October 27 automatically, with no second meeting needed.",
    "Beta customer migrations start October 14 in waves of three workspaces, Helix first.",
    "The Acme pilot runs on the launch build only; no custom build for Acme.",
  ],
  takeaways: [
    "Azure AD multi-tenant apps are the single largest technical risk; Okta and Google Workspace are done.",
    "The dashboard regression is 1.3 seconds at p95, down from 4.1, and needs one more index change to reach 900 ms.",
    "Three enterprise deals worth about $410K are waiting on SSO, including Acme at $96K.",
    "Support expects ticket volume to double in launch week; two contractors are booked for October 19 to 30.",
  ],
  topics: [
    ["00:00", "Go/no-go framing"],
    ["04:30", "SSO readiness"],
    ["15:10", "Dashboard performance"],
    ["24:00", "Launch campaign"],
    ["33:20", "Sales & the Acme pilot"],
    ["41:30", "Beta migrations & support"],
    ["51:15", "Gates & fallback"],
    ["58:40", "Owners recap"],
  ],
  actions: [
    ["Fix Azure AD multi-tenant sign-in and rerun the beta tenants", "priya", "2026-10-09"],
    ["Ship the composite index change and publish p95 numbers daily", "marcus", "2026-10-12"],
    ["Prepare two versions of the launch post: full SSO and Azure AD beta", "tom", "2026-10-08"],
    ["Confirm Acme's pilot runs on the launch build and update the forecast", "diego", "2026-10-02"],
    ["Schedule beta migrations in waves of three, starting with Helix", "emily", "2026-10-06"],
    ["Book two support contractors for October 19 to 30", "emily", "2026-09-26", true],
    ["Send the go/no-go gate criteria to the whole company", "olivia", "2026-09-23", true],
    ["Add a launch-week pricing FAQ for the sales team", "sarah", "2026-10-07"],
    ["Run the October 13 gate review and make the call", "hammad", "2026-10-13"],
  ],
  highlights: [
    ["06:05", "Azure AD is the real risk", "Okta and Google Workspace are done; multi-tenant Azure AD apps still fail sign-in.", "hammad"],
    ["19:45", "Performance at 1.3s, target 900ms", "One more composite index should close the gap; daily numbers from Marcus.", "olivia"],
    ["52:10", "Conditional go with automatic fallback", "Two gates on October 13; missing performance moves launch to the 27th without another meeting.", "hammad"],
  ],
  suggestedQuestions: [
    "What are the launch gates?",
    "What's the status of Azure AD SSO?",
    "When do beta migrations start?",
  ],
  lines: [
    ["00:08", "olivia", "Thanks for making time, everyone. This is the go/no-go for October twentieth. I want a clear answer by the end of the hour, and if it's a no, I want to know exactly what would turn it into a yes."],
    ["00:40", "hammad", "Here's how I'd like to run it. Each area gives status, the one risk that worries them most, and what they need from the room. Engineering first, then marketing, sales, and customer success. Then we set the gates."],
    ["01:32", "olivia", "Good. Keep it tight. Priya, you're up."],
    ["04:30", "priya", "SSO status. SAML is feature-complete for Okta and Google Workspace. Both pass every test tenant we have, including the two beta customers who volunteered."],
    ["05:18", "sarah", "That's better than I expected. What about Azure AD? That's what Acme and Brightline both run."],
    ["06:05", "priya", "Azure AD is the real risk. Single-tenant apps work. Multi-tenant apps fail sign-in because the issuer claim varies per tenant, and we validate it too strictly. I know the fix, but it touches token validation, so I want it reviewed properly."],
    ["07:20", "marcus", "How long for the fix plus review?"],
    ["07:44", "priya", "Three days to write, two to review and test against the beta tenants. So realistically October ninth if nothing else surprises us."],
    ["08:30", "diego", "If Azure AD slips, Acme slips. Their whole company signs in through Azure AD. That's a ninety-six thousand dollar deal."],
    ["09:15", "olivia", "Understood. Priya, what would you need to make the ninth safer?"],
    ["09:40", "priya", "Ben for a week. He wrote the original token code, and he can do the review in parallel instead of after."],
    ["10:20", "marcus", "Ben's on the performance work. I can give you Ben from Monday if the contractor starts on the index work at the same time."],
    ["11:05", "hammad", "Let's hold that trade until we hear the performance numbers. Marcus, go ahead."],
    ["15:10", "marcus", "Dashboard performance. The regression from last sprint had p95 at four point one seconds. We're down to one point three. The target for launch is nine hundred milliseconds."],
    ["16:02", "tom", "What's still slow? I'm demoing dashboards at the summit, and I'd love to know if I should avoid anything."],
    ["16:35", "marcus", "Filters on large workspaces. Anything with more than about fifty thousand rows and three or more filters. The contractor found a missing composite index; that alone should get us under a second."],
    ["17:40", "emily", "Helix is exactly that shape. They were the ones who reported it."],
    ["18:10", "marcus", "Right, and they've agreed to be our test workspace. We'll get real numbers from them, not just synthetic ones."],
    ["19:45", "olivia", "So performance is at one point three seconds, target nine hundred, and one more index change should close it. Marcus, I want those numbers published every day until launch."],
    ["20:30", "marcus", "Daily p95 in the launch channel, starting tomorrow. And yes, if the contractor stays on the index, Ben can move to SSO review on Monday."],
    ["21:05", "priya", "That works for me. With Ben reviewing in parallel, the ninth is solid."],
    ["24:00", "tom", "Launch campaign. The data summit keynote is October twentieth, and the launch post, the webinar, and the customer email are all drafted around SSO in Pro-plus."],
    ["24:52", "sarah", "Is the pricing page ready? I don't want Pro-plus announced without the page live."],
    ["25:20", "tom", "Copy is final, design is final, it ships behind a flag. The one open question is how we talk about Azure AD if it isn't ready."],
    ["26:15", "hammad", "What are the options?"],
    ["26:40", "tom", "Option one, we say SSO for Okta, Google Workspace, and Azure AD, and hope. Option two, we say Okta and Google Workspace, with Azure AD in beta. I'd rather write both posts now than scramble on the nineteenth."],
    ["27:35", "olivia", "Write both. I never want marketing promising something engineering hasn't shipped."],
    ["28:10", "tom", "I'll have two versions of the launch post ready by October eighth."],
    ["29:30", "sarah", "One more marketing thing: the webinar. Can we keep it flexible? If we fall back to the twenty-seventh, I'd rather move the webinar than cancel it."],
    ["30:05", "tom", "The webinar platform lets us reschedule for free until forty-eight hours before. So we're flexible until the eighteenth."],
    ["33:20", "diego", "Sales. Three enterprise deals are waiting on SSO, about four hundred ten thousand in total. Acme is the biggest at ninety-six thousand, and they want a pilot the week of launch."],
    ["34:15", "sarah", "Are they asking for anything non-standard?"],
    ["34:40", "diego", "They asked for a custom build with their Azure AD setup preconfigured. I told them I'd check, but I don't love it."],
    ["35:22", "olivia", "No custom builds. The Acme pilot runs on the launch build, same as everyone. If Azure AD is in beta, they're in the beta."],
    ["36:05", "diego", "That's fair, and honestly easier to sell. I'll confirm with Jordan this week and update the forecast."],
    ["37:10", "sarah", "Also, launch-week discounting. I want the fifteen percent cap enforced even with launch pressure. I'll add a pricing FAQ so reps don't improvise."],
    ["38:05", "diego", "A written FAQ would help. Half the discount requests come from reps not knowing what they're allowed to offer."],
    ["41:30", "emily", "Customer success. Eleven beta workspaces need to migrate to the new tiers. The one-click upgrade Marcus built works; we tested it on our own workspace yesterday."],
    ["42:25", "hammad", "When do you want to start?"],
    ["42:50", "emily", "October fourteenth, in waves of three workspaces, Helix first because they're the most engaged. That leaves room to fix anything before launch day."],
    ["43:40", "olivia", "Good. And support volume?"],
    ["44:05", "emily", "Based on the last launch, tickets roughly double in launch week. I've already booked two support contractors from October nineteenth to the thirtieth."],
    ["45:10", "priya", "Can support get an SSO troubleshooting guide? Most tickets will be misconfigured identity providers, not bugs."],
    ["45:45", "emily", "Yes, please. If you send me the common failure cases, my team will turn them into a guide."],
    ["47:20", "marcus", "And Brightline? They need the BAA before they can pilot at all."],
    ["47:55", "olivia", "Legal confirmed the BAA template this morning. That's unblocked; Emily, you can loop them into the second migration wave."],
    ["51:15", "hammad", "Okay, gates. Here's my proposal. Two gates, checked on October thirteenth. Gate one: dashboard p95 under nine hundred milliseconds on Helix. Gate two: Azure AD sign-in passing on all beta tenants."],
    ["52:10", "hammad", "If both pass, we go on the twentieth. If Azure AD fails, we still launch, with Azure AD labelled beta. If performance fails, launch moves to the twenty-seventh automatically, no second meeting."],
    ["53:05", "olivia", "Why treat them differently?"],
    ["53:30", "hammad", "Because a slow product hurts every customer, and a beta label on one identity provider only affects a few. Performance is the one we can't compromise on."],
    ["54:20", "sarah", "I agree with that logic. Customers forgive a beta label. They don't forgive slow dashboards."],
    ["55:00", "olivia", "Then it's decided. Conditional go for October twentieth, gates on the thirteenth, automatic fallback to the twenty-seventh if performance misses. I'll send the criteria to the whole company tonight."],
    ["55:45", "diego", "Can I share the gates with Acme? It'll help them plan the pilot."],
    ["56:10", "olivia", "Share the dates, not the internal numbers."],
    ["58:40", "hammad", "Owners, quickly. Priya: Azure AD fix by the ninth. Marcus: index change and daily numbers. Tom: two launch posts by the eighth. Diego: Acme on the launch build. Emily: migration waves from the fourteenth. Sarah: pricing FAQ. I'll run the gate review on the thirteenth."],
    ["1:00:20", "olivia", "Thanks, all. This is what a launch meeting should look like."],
    ["1:01:05", "tom", "I'll post the recording and the notes in the launch channel."],
  ],
});
