import { defineMeeting } from "./builders";

export const acmeProductDemo = defineMeeting({
  id: "acme-product-demo",
  title: "Acme Product Demo",
  date: "2026-09-22T14:00:00Z",
  duration: "46:20",
  meetingType: "Sales",
  platform: "zoom",
  hostId: "diego",
  participants: ["diego", "hammad", "jordan", "lena"],
  template: "sales",
  tags: ["acme", "demo", "sso", "pilot"],
  tone: "Positive · high buyer engagement",
  summary:
    "Diego and Hammad demoed Northstack to Acme Corp's operations and IT security leads. Acme's weekly reporting is manual and four days stale, and a carrier delay went unnoticed for nine days last quarter. Real-time dashboards, threshold alerts, and row-level permissions resonated strongly. Security requires Azure AD SSO and a SOC 2 report; both sides agreed to a free 30-day, 25-seat pilot on real Oracle data.",
  keyDecisions: [
    "Acme will run a free 30-day pilot with 25 seats connected to their Oracle warehouse data.",
    "Acme's security review runs in parallel with the pilot rather than before it.",
    "Pilot success means an automated Monday report plus carrier-delay alerts within a day.",
  ],
  takeaways: [
    "The pain is acute: two analysts spend half their week on manual reports and one-off requests.",
    "Azure AD SSO is a hard requirement; the lack of SCIM is flagged but not a pilot blocker.",
    "Estimated deal size is about $27K/year on Pro+, within Jordan's approval authority.",
  ],
  topics: [
    ["00:00", "Introductions"],
    ["03:10", "Acme's current reporting workflow"],
    ["09:40", "Live dashboard demo"],
    ["21:30", "Security & SSO requirements"],
    ["30:15", "Pricing & packaging"],
    ["38:50", "Pilot plan & next steps"],
  ],
  actions: [
    ["Send SOC 2 Type II report and DPA to Lena", "diego", "2026-09-22", true],
    ["Send the pilot agreement to Jordan", "diego", "2026-09-24"],
    ["Schedule the pilot kickoff for next Tuesday", "diego", "2026-09-25"],
    ["Enable Acme's workspace on the SSO early-access build", "hammad", "2026-09-29"],
    ["Build the Monday operations and carrier-delay dashboards", "hammad", "2026-10-02"],
  ],
  highlights: [
    ["03:32", "Manual reporting is four days stale", "Two analysts export to spreadsheets every Monday; managers see numbers four days late.", "diego"],
    ["11:48", "Alerting would have caught the carrier delay", "Threshold alerts to Slack resonated immediately with Jordan.", "hammad"],
    ["21:30", "Azure AD SSO is a hard requirement", "Lena won't onboard any tool without SSO.", "diego"],
    ["32:05", "30-day, 25-seat pilot", "Free pilot connected to Acme's real Oracle data.", "diego"],
  ],
  suggestedQuestions: [
    "What does Acme need for security approval?",
    "What are the next steps?",
    "What pricing did Diego quote?",
  ],
  lines: [
    ["00:08", "diego", "Thanks for making the time, Jordan, Lena. I've got Hammad, our head of product, with me so we can go deep on anything roadmap-related."],
    ["00:35", "jordan", "Great. Quick context from our side — I run operations for our three distribution centers, and Lena is here because anything we buy has to get through security review."],
    ["01:20", "lena", "Right. I'll mostly be listening until we get to identity and data handling."],
    ["03:10", "diego", "Jordan, walk us through how your team gets reporting today."],
    ["03:32", "jordan", "Honestly, it's painful. Every Monday two analysts export from our warehouse system into spreadsheets, clean it up by hand, and email a deck to the regional managers. By the time anyone reads it, the numbers are four days old."],
    ["04:55", "hammad", "How many people consume those reports?"],
    ["05:10", "jordan", "About sixty managers, plus the exec team. And every one of them asks for a slightly different cut, so the analysts spend half their week on one-off requests."],
    ["06:40", "jordan", "The other problem is we can't see issues until it's too late. Last quarter a carrier delay sat unnoticed for nine days because nobody was looking at the right chart."],
    ["09:40", "diego", "Let me show you what that looks like in Northstack. This is a sandbox connected to a sample warehouse feed — it refreshes every five minutes."],
    ["10:25", "hammad", "The thing I'd point out is the alerting. You can set a threshold — say, on-time shipments below ninety-two percent — and it'll post to Slack or email the regional owner automatically."],
    ["11:48", "jordan", "That would have caught the carrier delay. Can each regional manager only see their own sites?"],
    ["12:15", "hammad", "Yes, row-level permissions. You define the rule once, like region equals the manager's region, and every dashboard respects it."],
    ["14:30", "jordan", "I love that. That alone would kill most of the one-off requests."],
    ["17:05", "jordan", "How long does it take to connect a system like ours? We're on a fairly old Oracle setup."],
    ["17:40", "hammad", "Oracle is a supported connector. Typical setup is a day or two, and most of that is your team getting us a read-only user."],
    ["21:30", "lena", "Okay, my turn. Do you support SSO? We're an Azure AD shop, and we don't onboard any tool without it."],
    ["21:55", "hammad", "SAML SSO with Azure AD, Okta, and Google Workspace ships in our Pro-plus tier on October twentieth. We can put your workspace on the early access build if you want to test before then."],
    ["23:10", "lena", "What about SCIM for user provisioning? Deprovisioning is the part auditors care about."],
    ["23:40", "hammad", "SCIM is on the enterprise roadmap for later this year. At launch, deprovisioning works through SSO — if someone's removed from Azure AD, they can't sign in."],
    ["25:02", "lena", "That's workable for a pilot, but I'll flag it. I'll also need your SOC 2 Type II report and a data processing agreement."],
    ["25:30", "diego", "I'll send both today after this call."],
    ["30:15", "jordan", "Let's talk budget. What does this cost for roughly sixty viewers and five builders?"],
    ["30:48", "diego", "For that footprint you'd be on Pro-plus. List pricing is thirty-eight dollars per seat per month, and for a team your size we'd typically land around twenty-seven thousand a year."],
    ["31:40", "jordan", "That's within what I can approve myself if we can prove it out first. Is a pilot possible?"],
    ["32:05", "diego", "Absolutely. We'd do a thirty-day pilot with twenty-five seats, free, connected to your real Oracle data."],
    ["38:50", "jordan", "Here's what success looks like for me: the Monday report is automated, and regional managers get alerted on carrier delays within a day."],
    ["39:40", "hammad", "That's very achievable. We'll build those two dashboards with your analysts in the first week."],
    ["41:15", "lena", "Security review usually takes us two weeks, so let's start that in parallel."],
    ["42:30", "diego", "Perfect. I'll send the pilot agreement by Thursday, and let's schedule a kickoff for next Tuesday."],
    ["44:10", "jordan", "Sounds good. Honestly, this is the most promising demo we've seen this quarter."],
  ],
});

export const customerDiscovery = defineMeeting({
  id: "customer-discovery-brightline",
  title: "Customer Discovery: Brightline Health",
  date: "2026-09-17T11:00:00Z",
  duration: "41:30",
  meetingType: "Research",
  platform: "zoom",
  hostId: "hammad",
  participants: ["hammad", "aisha", "rachel"],
  template: "research",
  tags: ["discovery", "healthcare", "sso", "metrics"],
  tone: "Candid · exploratory",
  summary:
    "Hammad and Aisha interviewed Rachel Kim, Head of Data at Brightline Health, about how a six-person healthcare data team supports twelve clinics. The core pains are inconsistent metric definitions, unused dashboards, and a manual Excel 'last mile'. Compliance is decisive: a HIPAA BAA, Okta SSO, and view-level audit logs are prerequisites for any purchase. Rachel would pilot with two clinics if shared metrics, SSO, and a BAA are available.",
  keyDecisions: [
    "Brightline is open to a two-clinic pilot once SSO, shared metrics, and a BAA are available.",
    "Rachel will join a design review of the metrics layer in the coming weeks.",
  ],
  takeaways: [
    "SSO is a qualifying requirement in healthcare — Brightline's CISO rejected two vendors this year without it.",
    "Only about 8 of 40 dashboards are actually used; per-dashboard usage analytics is an unmet need.",
    "Shared metric definitions could save the data team a day per week.",
    "Plain-English alerts matter more to clinic managers than raw threshold alerts.",
  ],
  topics: [
    ["00:00", "Introductions"],
    ["02:30", "Team & data stack"],
    ["08:45", "Reporting pain points"],
    ["17:20", "Security & compliance"],
    ["26:10", "Wishlist"],
    ["35:00", "Wrap-up"],
  ],
  actions: [
    ["Send Rachel dates for a metrics layer design review", "aisha", "2026-09-24", true],
    ["Confirm BAA availability with legal", "hammad", "2026-09-30"],
    ["Write up discovery notes and share with product", "aisha", "2026-09-21", true],
    ["Scope dashboard usage analytics as a Q4 candidate", "hammad", "2026-10-02"],
  ],
  highlights: [
    ["09:10", "Reconciling metric definitions", "Every clinic defines no-shows differently; the team spends more time reconciling than analyzing.", "aisha"],
    ["17:45", "SSO is non-negotiable in healthcare", "Brightline's CISO rejected two vendors this year for lacking SSO.", "hammad"],
    ["26:35", "Magic wand: shared metric definitions", "Define a metric once and reuse it everywhere — would save a day a week.", "aisha"],
  ],
  suggestedQuestions: [
    "What did Rachel say about SSO?",
    "What are Brightline's biggest pain points?",
    "What would it take to run a pilot?",
  ],
  lines: [
    ["00:15", "hammad", "Thanks for doing this, Rachel. No pitch today — we're trying to understand how data teams in healthcare actually work. Aisha from design is here too."],
    ["00:48", "rachel", "Happy to. I've done a lot of these, and the honest ones are the useful ones."],
    ["02:30", "rachel", "My team is six people. We support about four hundred clinicians and the operations org across twelve clinics. Our stack is Snowflake, dbt, and, unfortunately, a lot of Excel."],
    ["03:40", "aisha", "Where does Excel come in?"],
    ["03:55", "rachel", "The last mile. Clinic managers don't log into BI tools. They want a spreadsheet in their inbox. So we export, and then the numbers drift because people edit them."],
    ["08:45", "hammad", "What's the most painful part of the week for your team?"],
    ["09:10", "rachel", "Answering the same question twelve different ways. Every clinic manager wants no-show rates, but each one defines a no-show differently. We spend more time reconciling definitions than analyzing."],
    ["11:02", "rachel", "And dashboards go stale. We built forty dashboards last year, and I'd guess eight are actually used."],
    ["12:30", "aisha", "How do you know which ones are used?"],
    ["12:48", "rachel", "We don't, really. That's part of the problem. I'd love usage data per dashboard so I can retire the dead ones."],
    ["17:20", "hammad", "How do security and compliance shape what tools you can buy?"],
    ["17:45", "rachel", "Everything touches patient data, so HIPAA is table stakes. We need a BAA, SSO through Okta, and audit logs of who viewed what. SSO is non-negotiable — our CISO rejected two vendors this year for not having it."],
    ["19:30", "rachel", "Honestly, SSO isn't a feature for us, it's a checkbox that decides whether we even talk to you."],
    ["20:15", "hammad", "That's consistent with what we're hearing. Do you need SCIM as well?"],
    ["20:40", "rachel", "It would be nice, but we manage provisioning manually today for most tools. SSO and audit logs are the must-haves."],
    ["26:10", "aisha", "If you had a magic wand, what would the product do?"],
    ["26:35", "rachel", "Shared metric definitions. Define no-show once, and every dashboard and every export uses it. That would save my team a day a week."],
    ["28:20", "rachel", "Second, alerts in plain English. Not 'metric exceeded threshold' — tell the clinic manager 'your no-show rate is twice the network average this week.'"],
    ["30:05", "rachel", "And third, scheduled exports that stay linked to the source, so when someone opens the spreadsheet it's actually current."],
    ["32:40", "hammad", "If we had shared metrics and SSO, would that be enough to run a pilot?"],
    ["33:05", "rachel", "Add a BAA and yes. I'd want to try it with two clinics first."],
    ["35:00", "aisha", "Would you be up for a design review of our metrics layer in a few weeks?"],
    ["35:20", "rachel", "Definitely. Send me a few dates."],
  ],
});

export const investorDiscussion = defineMeeting({
  id: "investor-update-foundry",
  title: "Investor Discussion: Foundry Ventures",
  date: "2026-09-16T16:00:00Z",
  duration: "48:50",
  meetingType: "Investor",
  platform: "zoom",
  hostId: "olivia",
  participants: ["olivia", "hammad", "david"],
  template: "general",
  tags: ["investors", "metrics", "fundraising"],
  tone: "Supportive · strategic",
  summary:
    "Olivia and Hammad updated David Okafor (Foundry Ventures) on Q3: $4.2M ARR, 118% net revenue retention, and 26 months of runway. Discussion focused on the enterprise motion — SSO was cited in six of seven lost Q3 enterprise deals and ships October 20 in a new Pro+ tier. David recommended landing three enterprise logos by year end and starting Series B relationship-building in January, with the raise itself targeted for Q2.",
  keyDecisions: [
    "Series B fundraising will not start before Q2 next year.",
    "Goal: three enterprise logos live by year end, with one public case study.",
    "Relationship-building with prospective Series B partners begins in January.",
  ],
  takeaways: [
    "Expansion is seat-driven: teams grow from about 5 builders to about 40 viewers within a year.",
    "The shared metrics layer is positioned as the next platform bet after SSO.",
    "Enterprise qualified pipeline stands at $1.8M, led by Acme and Helix.",
  ],
  topics: [
    ["00:00", "Catch-up"],
    ["02:40", "Q3 metrics"],
    ["12:20", "Enterprise motion"],
    ["23:30", "Product roadmap"],
    ["33:10", "Fundraising timing"],
    ["43:00", "Asks"],
  ],
  actions: [
    ["Send three intros to VPs of Data at logistics companies", "david", "2026-09-19", true],
    ["Connect Olivia with a portfolio pricing advisor", "david", "2026-09-23"],
    ["Draft the Q4 enterprise case study plan with Helix", "olivia", "2026-10-05"],
    ["Share updated board metrics after the October launch", "olivia", "2026-11-03"],
  ],
  highlights: [
    ["02:40", "Q3: $4.2M ARR, 118% NRR", "ARR up from $3.1M at the start of the year.", "olivia"],
    ["12:45", "SSO cited in 6 of 7 lost deals", "SAML SSO ships October 20 in the new Pro+ tier.", "hammad"],
    ["19:15", "Three enterprise logos by year end", "David's advice for the next round's narrative.", "olivia"],
  ],
  suggestedQuestions: [
    "What were the Q3 metrics?",
    "When is the Series B?",
    "What advice did David give?",
  ],
  lines: [
    ["00:20", "david", "Good to see you both. I read the board memo — congrats on the quarter. I want to spend most of the time on enterprise."],
    ["02:40", "olivia", "Headline numbers: we ended Q3 at four point two million ARR, up from three point one at the start of the year. Net revenue retention is a hundred and eighteen percent."],
    ["03:55", "david", "What's driving the expansion?"],
    ["04:10", "olivia", "Seat growth inside existing accounts, mostly. Teams start with five builders and a year later have forty viewers."],
    ["06:30", "david", "And burn?"],
    ["06:45", "olivia", "Net burn is about three hundred and ten thousand a month. We have twenty-six months of runway at the current plan."],
    ["12:20", "david", "Talk to me about enterprise. Last time you said SSO was the blocker."],
    ["12:45", "hammad", "It still is, but not for long. We lost seven enterprise deals in Q3 and six of them cited SSO. We ship SAML SSO on October twentieth in a new Pro-plus tier."],
    ["14:10", "david", "Why a new tier instead of just enterprise?"],
    ["14:30", "hammad", "Mid-market teams need SSO for their own security reviews but won't sign a forty-five thousand dollar contract. Pro-plus lets us capture them without discounting enterprise."],
    ["16:40", "david", "What does the enterprise pipeline look like?"],
    ["17:00", "olivia", "One point eight million in qualified pipeline. Acme and Helix are the two biggest, and Helix is already onboarding."],
    ["19:15", "david", "My advice: get three enterprise logos live by year end and make one of them a case study. That's the story the next round will want."],
    ["23:30", "hammad", "On roadmap, after SSO the big bet is a shared metrics layer. Every discovery call — healthcare, logistics — comes back to inconsistent definitions."],
    ["25:10", "david", "Is that a feature or a platform shift?"],
    ["25:30", "hammad", "A platform shift, honestly. It's what makes us harder to rip out."],
    ["33:10", "david", "Fundraising. When are you thinking about the Series B?"],
    ["33:35", "olivia", "Not before Q2 next year. I want two quarters of enterprise data and NRR above one-twenty."],
    ["35:05", "david", "That's disciplined. I'd start relationship-building in January anyway. The best partners take a few months to warm up."],
    ["43:00", "olivia", "Two asks. Intros to VPs of Data at logistics companies, and a sanity check on our enterprise pricing before January."],
    ["43:40", "david", "Easy. I'll send three intros this week, and I'll connect you with a pricing advisor from our portfolio."],
    ["47:20", "olivia", "Thank you, David. Always helpful."],
  ],
});

export const enterpriseOnboarding = defineMeeting({
  id: "enterprise-onboarding-helix",
  title: "Enterprise Onboarding: Helix Logistics",
  date: "2026-09-14T10:00:00Z",
  duration: "46:30",
  meetingType: "Onboarding",
  platform: "teams",
  hostId: "emily",
  participants: ["emily", "priya", "sam", "grace"],
  template: "general",
  tags: ["helix", "onboarding", "sso", "scim"],
  tone: "Structured · positive",
  summary:
    "Emily and Priya kicked off enterprise onboarding with Helix Logistics. Rather than migrating ~300 legacy reports, the teams will rebuild the ~40 actively used ones, with Northstack building the first 20 by October 2. Okta SSO with group-based role mapping is available immediately via the early access build. Until SCIM ships, deprovisioning will rely on one-hour SSO sessions plus a weekly active-users report.",
  keyDecisions: [
    "Only the ~40 actively used reports will be rebuilt; the rest are retired.",
    "Okta SSO is configured before inviting the broader Helix team.",
    "Session length is set to one hour, plus a weekly active-users export, as a bridge until SCIM.",
    "Success means every regional manager uses a dashboard weekly and the legacy tool is retired by November 1.",
  ],
  takeaways: [
    "Helix's pilot cut weekly report prep from two days to two hours — strong case study material.",
    "Automated deprovisioning within 24 hours is an audit requirement; SCIM demand is real.",
    "Viewer training must be recorded for shift workers across three time zones.",
  ],
  topics: [
    ["00:00", "Kickoff"],
    ["03:20", "Data migration"],
    ["13:40", "SSO with Okta"],
    ["22:30", "SCIM & deprovisioning"],
    ["30:15", "Training plan"],
    ["40:00", "Success criteria"],
  ],
  actions: [
    ["Send Okta metadata URL and SSO setup guide to Grace", "priya", "2026-09-14", true],
    ["Build the first 20 Helix dashboards", "emily", "2026-10-02"],
    ["Set up a weekly active-users report for Helix admins", "emily", "2026-09-18", true],
    ["Schedule the builder workshop and recorded viewer orientation", "emily", "2026-09-26"],
    ["Send Friday onboarding progress reports to Sam", "emily", "2026-09-25"],
  ],
  highlights: [
    ["00:45", "Pilot: two days → two hours", "Helix cut weekly report prep from two days to about two hours.", "emily"],
    ["22:30", "24-hour deprovisioning requirement", "Grace needs leavers removed from every tool within 24 hours for audit.", "priya"],
    ["40:30", "Onboarding success criteria", "Weekly dashboard use by every regional manager; legacy tool retired by Nov 1.", "emily"],
  ],
  suggestedQuestions: [
    "How will deprovisioning work without SCIM?",
    "What's the migration plan?",
    "How is onboarding success measured?",
  ],
  lines: [
    ["00:12", "emily", "Welcome officially to Northstack! Today's goal is a clear onboarding plan for the next thirty days."],
    ["00:45", "sam", "Excited to get going. Our pilot went really well — we cut weekly report prep from two days to about two hours."],
    ["03:20", "emily", "Data migration first. You have about three hundred saved reports in your old tool. We don't recommend migrating all of them."],
    ["04:10", "sam", "Agreed, most of them are dead. We checked usage — about forty are opened monthly."],
    ["05:05", "emily", "Then we'll rebuild those forty as Northstack dashboards. Our team will do the first twenty, and we'll train your analysts on the rest."],
    ["07:30", "sam", "Timeline?"],
    ["07:45", "emily", "First twenty dashboards by October second, the rest by mid-October with your team."],
    ["13:40", "grace", "SSO. We use Okta for everything. I'd like to get that configured before we invite the broader team."],
    ["14:15", "priya", "You're on our early access build, so SAML with Okta is available now. I'll send you the metadata URL and a setup guide today."],
    ["15:30", "grace", "Do you support group-based role mapping? I want the finance group to land as viewers automatically."],
    ["16:05", "priya", "Yes — map Okta groups to Northstack roles in the SSO settings. Viewer, builder, or admin."],
    ["22:30", "grace", "Deprovisioning. When someone leaves, I need them out of every tool within twenty-four hours. That's an audit requirement."],
    ["23:15", "priya", "Honest answer: SCIM isn't available until later this year. Today, anyone removed from Okta loses access at their next sign-in, because every session re-authenticates through SSO."],
    ["24:30", "grace", "Sessions last how long?"],
    ["24:45", "priya", "Twelve hours by default. You can set it as low as one hour for your workspace."],
    ["25:40", "grace", "One hour works for audit if I can export a list of active users weekly."],
    ["26:10", "emily", "We can add a weekly active-users report to your admin email. I'll set that up."],
    ["30:15", "emily", "Training. I'd propose two sessions: a builder workshop for your six analysts and a thirty-minute viewer orientation for everyone else."],
    ["31:20", "sam", "Can we record the viewer session? We have shift workers across three time zones."],
    ["31:40", "emily", "Of course. We'll record it and share it in your workspace."],
    ["40:00", "emily", "Last thing — how will we know onboarding succeeded?"],
    ["40:30", "sam", "Every regional manager uses a Northstack dashboard at least weekly, and we retire the old tool by November first."],
    ["42:10", "emily", "Great. I'll track weekly active viewers and send you a progress report every Friday."],
    ["45:00", "sam", "Perfect. Thanks, Emily and Priya — this is a really clear plan."],
  ],
});
