import { defineMeeting } from "./builders";

export const salesPipelineReview = defineMeeting({
  id: "sales-pipeline-review",
  title: "Sales Pipeline Review",
  date: "2026-09-18T10:00:00Z",
  duration: "34:15",
  meetingType: "Sales",
  platform: "google-meet",
  hostId: "diego",
  participants: ["diego", "sarah", "olivia", "emily"],
  template: "sales",
  tags: ["pipeline", "forecast", "discounts"],
  tone: "Direct · forecast-focused",
  summary:
    "The team reviewed $1.8M in qualified pipeline across twelve opportunities, with a $640K Q4 commit and $890K best case. Acme Corp hinges on Azure AD SSO shipping October 20; Helix Logistics has a ~30-seat, ~$14K expansion opportunity; Brightline Health needs a signed BAA before piloting. Leadership introduced a 15% cap on standard discounts after last quarter's average discount reached 19%.",
  keyDecisions: [
    "Standard discounts are capped at 15%; anything higher needs CEO sign-off and a written reason.",
    "Northstack will sign BAAs for healthcare customers; legal will confirm the template.",
    "Helix will be offered a manual deprovisioning report as a bridge until SCIM ships.",
    "The Q4 commit is $640K, with Acme held in best case until its security review begins.",
  ],
  takeaways: [
    "SSO timing directly determines whether Acme closes in Q4 or slips to Q1.",
    "Last quarter's 19% average discount is eroding the enterprise price point.",
    "The Helix finance team expansion adds about 30 seats if onboarding goes smoothly.",
  ],
  topics: [
    ["00:00", "Pipeline overview"],
    ["03:45", "Acme Corp"],
    ["10:20", "Helix Logistics expansion"],
    ["16:30", "Brightline Health"],
    ["22:10", "Discounting policy"],
    ["29:30", "Forecast"],
  ],
  actions: [
    ["Confirm the BAA template with legal", "olivia", "2026-09-25"],
    ["Propose a manual deprovisioning report to Helix", "emily", "2026-09-22", true],
    ["Add a discount approval field to the CRM", "sarah", "2026-09-30"],
    ["Update the Q4 forecast after the Acme pilot kickoff", "diego", "2026-10-02"],
  ],
  highlights: [
    ["05:05", "Acme depends on SSO timing", "Acme's IT is Azure AD-only; if SSO slips past October, the deal slips to Q1.", "diego"],
    ["24:15", "15% discount cap", "Anything above 15% now needs CEO sign-off and a written reason.", "sarah"],
  ],
  suggestedQuestions: [
    "What is the Q4 commit?",
    "What did we decide about discounts?",
    "What's the risk on the Helix expansion?",
  ],
  lines: [
    ["00:12", "diego", "Pipeline's at one point eight million qualified, up from one point three a month ago. Twelve active opportunities, four in late stage."],
    ["01:30", "olivia", "What's our Q4 commit?"],
    ["01:45", "diego", "Six hundred and forty thousand commit, eight-ninety best case."],
    ["03:45", "diego", "Acme Corp. The demo is scheduled for the twenty-second. Jordan Mills is the champion — ops director, very frustrated with manual reporting."],
    ["04:50", "sarah", "What's the blocker risk?"],
    ["05:05", "diego", "Security. Their IT team is Azure AD-only. If SSO slips past October, Acme slips to Q1."],
    ["06:20", "olivia", "SSO isn't slipping. Tell them October twentieth with confidence."],
    ["10:20", "emily", "Helix is going well. They're onboarding now, and Sam Patel already asked about adding their finance team — that's another thirty seats."],
    ["11:35", "diego", "That's an expansion worth about fourteen thousand a year. Can we close it this quarter?"],
    ["12:00", "emily", "If onboarding goes smoothly, yes. The risk with Helix is their SCIM request. Grace, their admin, wants automated deprovisioning."],
    ["13:15", "sarah", "SCIM is enterprise-only and not shipping until later. Can we offer a manual deprovisioning report as a bridge?"],
    ["13:50", "emily", "I think Grace would accept that for now. I'll propose it."],
    ["16:30", "diego", "Brightline Health. Hammad did a discovery call with Rachel Kim, their head of data. They want SSO, a BAA, and shared metrics."],
    ["17:40", "sarah", "Shared metrics is next year. Is that a deal-breaker?"],
    ["18:05", "diego", "Not for a two-clinic pilot. But the BAA is. Legal hasn't confirmed we'll sign one."],
    ["19:20", "olivia", "We'll sign BAAs. I'll get legal to confirm the template this week."],
    ["22:10", "sarah", "Discounting. We averaged a nineteen percent discount last quarter, and two deals went to twenty-five. That's eroding our enterprise price point."],
    ["23:30", "diego", "Those two were end-of-quarter pushes. I hear you, though."],
    ["24:15", "olivia", "New rule, effective now: standard discounts cap at fifteen percent. Anything above needs my sign-off and a written reason."],
    ["25:40", "sarah", "I'll put the guardrails in the pricing proposal so it's documented, and add a discount approval field in the CRM."],
    ["29:30", "diego", "Forecast call: I'm committing six-forty. Acme is in best case until security review starts."],
    ["30:45", "olivia", "Fine. Let's review again in two weeks, right after the Acme pilot kicks off."],
  ],
});

export const marketingPlanning = defineMeeting({
  id: "marketing-planning-launch",
  title: "Marketing Planning: October Launch",
  date: "2026-09-15T13:00:00Z",
  duration: "42:10",
  meetingType: "Marketing",
  platform: "google-meet",
  hostId: "tom",
  participants: ["tom", "sarah", "hammad", "aisha"],
  template: "general",
  tags: ["launch", "messaging", "pricing-page", "webinar"],
  tone: "Creative · collaborative",
  summary:
    "Marketing, growth, product, and design aligned on the October enterprise launch. The hero message will center on passing security reviews, with SSO as the lead proof point. The pricing page adds Pro+ as the highlighted plan while moving Enterprise into a separate 'Talk to sales' band. A launch webinar on October 22 will use a pre-recorded SSO demo with live Q&A, and Helix Logistics is the target launch case study.",
  keyDecisions: [
    "Hero message: 'Pass your security review on the first try', with SSO as the lead proof point.",
    "The pricing page shows three plan cards with Pro+ highlighted; Enterprise moves to a 'Talk to sales' band.",
    "The launch webinar on October 22 uses a pre-recorded SSO demo with live Q&A.",
    "Helix Logistics is the target enterprise case study for launch.",
  ],
  takeaways: [
    "Launch target: 200 qualified enterprise leads and 50 demo requests in the first month.",
    "The comparison table needs an explicit SSO row — it's the most common pricing-page chat question.",
    "Helix cut report prep from two days to two hours during their pilot.",
  ],
  topics: [
    ["00:00", "Launch goals"],
    ["05:30", "Messaging & positioning"],
    ["14:40", "Pricing page"],
    ["22:15", "Launch webinar"],
    ["30:20", "Customer case study"],
    ["37:50", "Timeline"],
  ],
  actions: [
    ["Draft launch messaging around security review", "tom", "2026-09-26"],
    ["Design the pricing page with Pro+ highlighted", "aisha", "2026-09-30"],
    ["Get Helix approval for the launch case study", "sarah", "2026-09-29"],
    ["Pre-record the SSO setup demo with Priya", "tom", "2026-10-13"],
    ["Send webinar invites", "tom", "2026-10-06"],
  ],
  highlights: [
    ["06:15", "Lead with the security review", "Security review is where enterprise deals die — make passing it the hero message.", "tom"],
    ["31:10", "Helix: two days to two hours", "Headline stat for the launch case study.", "sarah"],
  ],
  suggestedQuestions: [
    "What is the launch messaging?",
    "What changes on the pricing page?",
    "When is the webinar?",
  ],
  lines: [
    ["00:15", "tom", "Goal for this session: lock the launch plan for the enterprise release so we can start production next week."],
    ["00:50", "sarah", "The primary goal is pipeline. I want two hundred qualified enterprise leads from the launch, and fifty demo requests in the first month."],
    ["05:30", "tom", "Messaging. The current draft headline is 'Enterprise-ready analytics.' I think it's too generic."],
    ["06:15", "hammad", "What we've heard in every enterprise call is that security review is where deals die. What if we lead with that — 'Pass your security review on the first try'?"],
    ["07:40", "aisha", "I like that it's about the buyer's problem, not our features. It also sets up SSO, audit logs, and permissions as proof points."],
    ["09:10", "tom", "Okay, I'll draft around security review as the hero message, with SSO as the lead proof point."],
    ["14:40", "sarah", "Pricing page. We're adding Pro-plus, so the page goes from three columns to four. I'm worried about decision paralysis."],
    ["15:45", "aisha", "We could move Enterprise into a 'Talk to sales' band under the table. Three cards stay scannable."],
    ["16:50", "sarah", "Good. Pro-plus should be the highlighted plan — it's where we want mid-market to land."],
    ["18:30", "hammad", "And the comparison table needs an explicit SSO row. Half the pricing-page questions in chat are 'Do you have SSO?'"],
    ["22:15", "tom", "Webinar. I'm proposing October twenty-second, two days after launch, with Priya demoing SSO setup live."],
    ["23:20", "hammad", "Live identity demos are risky. Let's pre-record the setup and have Priya do live Q and A."],
    ["24:05", "tom", "Fair. Pre-recorded demo, live Q and A."],
    ["30:20", "tom", "Case study. We need an enterprise logo at launch. Helix is our best bet."],
    ["31:10", "sarah", "Emily says Sam Patel is enthusiastic. They cut report prep from two days to two hours in their pilot."],
    ["32:25", "hammad", "That's a great headline stat. Let's get their approval quickly — legal at logistics companies can be slow."],
    ["37:50", "tom", "Timeline: messaging final by the twenty-sixth, pricing page in review on the thirtieth, webinar invites out on October sixth."],
    ["39:20", "sarah", "If the launch moves to the twenty-seventh, everything shifts by a week except the webinar invites."],
    ["41:00", "tom", "Got it. I'll build the plan with both dates."],
  ],
});

export const weeklyOneOnOne = defineMeeting({
  id: "weekly-1-1-aisha",
  title: "Weekly 1:1 — Hammad / Aisha",
  date: "2026-09-21T15:30:00Z",
  duration: "27:40",
  meetingType: "1:1",
  platform: "google-meet",
  hostId: "hammad",
  participants: ["hammad", "aisha"],
  template: "one-on-one",
  tags: ["1:1", "growth", "workload"],
  tone: "Supportive · candid",
  summary:
    "Hammad and Aisha's weekly 1:1 covered recent wins, workload, and growth. Aisha's Brightline discovery notes were forwarded to the board, and the admin console roles page tested well with Helix. She is stretched across three workstreams, so the pricing page first pass will move to Tom's team. Hammad asked Aisha to share work earlier and offered her ownership of the metrics layer research program.",
  keyDecisions: [
    "Tom's team takes the first pass on the pricing page using Aisha's component specs.",
    "Aisha will own the metrics layer research program end to end.",
    "Aisha gets a standing twice-weekly slot with Priya until launch.",
  ],
  takeaways: [
    "Aisha's research synthesis is a recognized strength; the growth area is sharing work earlier.",
    "Design capacity is the constraint across the admin console, pricing page, and metrics research.",
    "Aisha found the Q4 strategy meeting format more valuable than status meetings.",
  ],
  topics: [
    ["00:00", "Check-in"],
    ["02:10", "Wins"],
    ["07:30", "Blockers"],
    ["15:20", "Feedback"],
    ["21:40", "Growth goals"],
  ],
  actions: [
    ["Ask Tom's team to take the pricing page first pass", "hammad", "2026-09-21", true],
    ["Set up a twice-weekly design handoff with Priya", "hammad", "2026-09-23"],
    ["Draft the metrics layer research plan", "aisha", "2026-10-02"],
    ["Share rough concepts in the design channel on Fridays", "aisha", "2026-09-25"],
  ],
  highlights: [
    ["07:30", "Stretched across three workstreams", "Admin console, pricing page, and metrics research — something will slip.", "hammad"],
    ["22:30", "Owning the metrics research program", "Aisha will own the research plan, recruiting, and the leadership readout.", "hammad"],
  ],
  suggestedQuestions: [
    "What blockers did Aisha raise?",
    "What feedback was given?",
    "What are Aisha's growth goals?",
  ],
  lines: [
    ["00:10", "hammad", "How are you doing? Last week looked intense."],
    ["00:25", "aisha", "Intense but good. I'm tired, but it's the productive kind of tired."],
    ["02:10", "aisha", "Biggest win: the Brightline discovery call. Rachel's comment about shared metric definitions reframed how I'm thinking about the whole metrics layer."],
    ["03:30", "hammad", "I saw your notes — they were excellent. Olivia forwarded them into the board deck."],
    ["04:15", "aisha", "Oh, that's great to hear. Also, the admin console roles page tested well with Helix. Grace finished every task without help."],
    ["07:30", "aisha", "Blocker: I'm the only designer on three workstreams — admin console, pricing page, and metrics layer research. Something is going to slip."],
    ["08:45", "hammad", "Which one would you drop if you had to?"],
    ["09:05", "aisha", "The pricing page is the most templated. Tom's team could take the first pass if I provide the component specs."],
    ["10:20", "hammad", "Let's do that. I'll talk to Tom today. Metrics research is the long-term bet, so I want to protect your time there."],
    ["12:10", "aisha", "The other blocker is engineering handoff. SSO designs are done, but I don't have a slot with Priya to walk through the edge cases."],
    ["13:00", "hammad", "I'll ask Marcus to set up a standing thirty minutes with Priya for you twice a week until launch."],
    ["15:20", "hammad", "Feedback for you: your research synthesis is the best on the team. Where I'd push you is sharing earlier — the admin console concepts sat in Figma a week before anyone saw them."],
    ["16:40", "aisha", "That's fair. I tend to wait until things feel finished."],
    ["17:25", "hammad", "Try posting rough work in the design channel on Fridays. Even half-baked concepts."],
    ["18:10", "aisha", "Okay, I'll try that. Feedback for you — the Q4 strategy meeting was the clearest one we've had. More of those, fewer status meetings."],
    ["21:40", "aisha", "Growth-wise, I want to lead a research program, not just run individual studies."],
    ["22:30", "hammad", "Then let's make the metrics layer research yours. You'd own the research plan, recruiting, and the readout to leadership."],
    ["23:50", "aisha", "I'd love that. I'll draft a research plan by next Friday."],
    ["26:10", "hammad", "Great. Same time next week."],
  ],
});

export const hiringInterview = defineMeeting({
  id: "hiring-interview-frontend",
  title: "Hiring Interview: Senior Frontend Engineer",
  date: "2026-09-18T14:00:00Z",
  duration: "44:30",
  meetingType: "Interview",
  platform: "zoom",
  hostId: "marcus",
  participants: ["marcus", "hammad", "nina"],
  template: "interview",
  tags: ["hiring", "frontend", "interview"],
  tone: "Structured · evaluative",
  summary:
    "Marcus and Hammad interviewed Nina Kowalski for the Senior Frontend Engineer role. Nina leads a dashboard platform used by ~40 engineers and previously cut render time for 200-widget dashboards from 11s to under 2s. In the design exercise she proposed viewport-based rendering, query deduplication, and permission-scoped caching — matching a bug the team recently fixed. She showed strong product judgment and design collaboration, and named over-owning work as a growth area.",
  keyDecisions: [
    "Advance Nina to the final round, with a design-collaboration session with Aisha.",
    "Interviewers submit written scorecards before the debrief.",
  ],
  takeaways: [
    "Strong performance engineering depth with measurable results and P95-focused thinking.",
    "Security-aware architecture: server-side permission scoping and permission-aware cache keys.",
    "Main concern: a tendency to over-own work instead of delegating, which Nina is actively working on.",
  ],
  topics: [
    ["00:00", "Introductions"],
    ["02:30", "Background"],
    ["09:15", "System design: dashboard rendering"],
    ["22:40", "Collaboration with design"],
    ["31:00", "Candidate questions"],
    ["40:30", "Debrief"],
  ],
  actions: [
    ["Submit interview scorecard", "marcus", "2026-09-19", true],
    ["Submit interview scorecard", "hammad", "2026-09-19", true],
    ["Schedule the final round with Aisha", "marcus", "2026-09-23"],
    ["Send the candidate follow-up email", "marcus", "2026-09-21", true],
  ],
  highlights: [
    ["04:10", "11s → 2s dashboard render", "Virtualized rendering and a shared query cache for 200-widget dashboards.", "marcus"],
    ["12:40", "Permission-scoped caching", "Never filter on the client; include permission scope in the cache key.", "marcus"],
    ["25:55", "Resolving design disagreements with data", "A/B tested chart animations and shipped both behaviors.", "hammad"],
  ],
  suggestedQuestions: [
    "What are Nina's strengths?",
    "Any concerns about the candidate?",
    "How did she approach the design exercise?",
  ],
  lines: [
    ["00:15", "marcus", "Hi Nina, thanks for joining. I'm Marcus, engineering manager, and this is Hammad, who leads product. We'll do background, a design exercise, then your questions."],
    ["02:30", "nina", "Sure. I'm a senior frontend engineer at a fintech company, five years there. I lead our charting and dashboard platform — about forty engineers build on top of it."],
    ["03:50", "hammad", "What's the thing you're proudest of there?"],
    ["04:10", "nina", "We had dashboards with two hundred widgets that took eleven seconds to render. I moved us to virtualized rendering and a shared query cache. We got it under two seconds."],
    ["06:20", "marcus", "How did you measure that?"],
    ["06:35", "nina", "Real user monitoring on interaction-to-next-paint and time-to-first-widget, broken down by dashboard size. The average was misleading — the P95 was what users felt."],
    ["09:15", "marcus", "Design exercise. Imagine a dashboard with fifty charts, each backed by a query, and row-level permissions per viewer. How would you architect the rendering?"],
    ["10:05", "nina", "First, I'd only fetch and render what's in the viewport, with a small overscan. Second, I'd dedupe queries — fifty charts often share maybe fifteen distinct queries."],
    ["12:40", "nina", "For permissions, I'd never filter on the client. The server resolves the viewer's scope, and the cache key includes the permission scope so nobody sees cached data they shouldn't."],
    ["14:25", "marcus", "That's exactly the bug we just fixed, actually. Good instinct."],
    ["16:10", "hammad", "What would you do if a product manager wants real-time updates on all fifty charts?"],
    ["16:40", "nina", "I'd ask what decision real-time enables. Usually it's two or three charts. Those get a streaming subscription, the rest refresh on an interval. Everyone's happy and the database survives."],
    ["22:40", "hammad", "Tell me about working with designers."],
    ["23:05", "nina", "I pair with design early, in the prototype stage. My best project came from sitting with a designer for a week and building the interaction model together in code instead of Figma."],
    ["25:30", "marcus", "Tell me about a disagreement with a designer."],
    ["25:55", "nina", "We disagreed on animated chart transitions. I thought they hurt performance; the designer thought they helped comprehension. We A/B tested it — the designer was right for small datasets, I was right for large ones. We shipped both behaviors."],
    ["28:40", "hammad", "What's a weakness you're working on?"],
    ["29:00", "nina", "I over-own things. I'll fix a problem myself instead of teaching someone else to. I've started pairing more deliberately with junior engineers."],
    ["31:00", "nina", "What does success look like in the first ninety days?"],
    ["31:25", "marcus", "Owning dashboard rendering performance end to end, and shipping the new admin console with Aisha."],
    ["33:10", "nina", "How do you balance enterprise feature requests against core product quality?"],
    ["33:40", "hammad", "Honestly, it's a tension. Right now SSO is our top priority, but we just approved a contractor so performance doesn't suffer."],
    ["40:30", "marcus", "Thanks, Nina. We'll get back to you within a few days."],
    ["41:30", "marcus", "Hammad, quick gut check now that she's dropped — I'd advance her to the final round."],
    ["42:10", "hammad", "Strong yes. Let's have her do a design-collaboration session with Aisha. Scorecards in before the debrief, please."],
  ],
});
